name: Update TFT Data

on:
  schedule:
    - cron: '30 23 * * *' # 23:30 UTC mỗi ngày
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Để pull các thay đổi mới nhất, tránh xung đột

      - name: Fetch Data from Workers
        run: |
          # Tạo thư mục public/data/auto nếu chưa có
          mkdir -p public/data/auto

          # Tạo danh sách file dựa trên ngày hiện tại và ngày trước đó
          TODAY=$(date +%d-%m-%Y)
          YESTERDAY=$(date -d "yesterday" +%d-%m-%Y)

          # Worker 1 (hocvientft): Tạo danh sách file data-DD-MM-YYYY.json
          DATA_FILES=(
            "data-${TODAY}.json"
            "data-${YESTERDAY}.json"
          )

          # Worker 2 (comp-hocvientft): Tạo danh sách file guides-DD-MM-YYYY.json
          GUIDES_FILES=(
            "guides-${TODAY}.json"
            "guides-${YESTERDAY}.json"
          )

          # Tải file từ Worker 1 (hocvientft)
          for filename in "${DATA_FILES[@]}"; do
            echo "Attempting to download $filename from hocvientft..."
            curl -X GET "https://hocvientft.hoquocdieu.workers.dev/?file=$filename" -o "public/data/auto/$filename" || echo "File $filename not found in hocvientft, skipping..."
          done

          # Tải file từ Worker 2 (comp-hocvientft)
          for filename in "${GUIDES_FILES[@]}"; do
            echo "Attempting to download $filename from comp-hocvientft..."
            curl -X GET "https://comp-hocvientft.hoquocdieu.workers.dev/?file=$filename" -o "public/data/auto/$filename" || echo "File $filename not found in comp-hocvientft, skipping..."
          done

      - name: Validate JSON Files
        run: |
          # Kiểm tra các file JSON tải về có hợp lệ không
          for file in public/data/auto/*.json; do
            if [ -f "$file" ]; then
              jq . "$file" > /dev/null || { echo "Invalid JSON in $file"; exit 1; }
              echo "Validated $file"
            fi
          done

      - name: Clean Old Files in public/data/auto
        run: |
          # Giữ lại 2 file data-*.json mới nhất, xóa các file cũ hơn
          ls -t public/data/auto/data-*.json 2>/dev/null | tail -n +3 | xargs -I {} rm -v {}
          # Giữ lại 2 file guides-*.json mới nhất, xóa các file cũ hơn
          ls -t public/data/auto/guides-*.json 2>/dev/null | tail -n +3 | xargs -I {} rm -v {}

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Pull trước khi commit để tránh xung đột
          git pull origin main --rebase
          # Kiểm tra xem thư mục public/data/auto có file không
          if ls public/data/auto/* 2>/dev/null; then
            git add public/data/auto/*
            if git diff --staged --quiet; then
              echo "No changes to commit"
              exit 0
            fi
            git commit -m "Update TFT data on $(date +'%d-%m-%Y')"
            git push
          else
            echo "No files found in public/data/auto to commit"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}