name: Update TFT Data

on:
  schedule:
    - cron: '30 23 * * *' # 23:30 UTC mỗi ngày
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Để pull các thay đổi mới nhất, tránh xung đột

      - name: Fetch Data from Workers
        run: |
          # Tạo thư mục public/data/auto nếu chưa có
          mkdir -p public/data/auto
          
          # Worker 1 (hocvientft)
          curl -X GET "https://hocvientft.hoquocdieu.workers.dev/?list-files" -o file-list-1.json || echo "[]" > file-list-1.json
          jq -r '.[] | select(test("^data-"))' file-list-1.json | sort -r | head -n 2 | while read filename; do
            curl -X GET "https://hocvientft.hoquocdieu.workers.dev/?file=$filename" -o "public/data/auto/$filename"
          done
          
          # Worker 2 (comp-hocvientft)
          curl -X GET "https://comp-hocvientft.hoquocdieu.workers.dev/?list-files" -o file-list-2.json || echo "[]" > file-list-2.json
          jq -r '.[] | select(test("^guides-"))' file-list-2.json | sort -r | head -n 2 | while read filename; do
            curl -X GET "https://comp-hocvientft.hoquocdieu.workers.dev/?file=$filename" -o "public/data/auto/$filename"
          done

      - name: Clean Old Files in public/data/auto
        run: |
          # Giữ lại 2 file data-*.json mới nhất, xóa các file cũ hơn
          ls -t public/data/auto/data-*.json 2>/dev/null | tail -n +3 | xargs -I {} rm -v {}
          # Giữ lại 2 file guides-*.json mới nhất, xóa các file cũ hơn
          ls -t public/data/auto/guides-*.json 2>/dev/null | tail -n +3 | xargs -I {} rm -v {}

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Pull trước khi commit để tránh xung đột
          git pull origin main --rebase
          # Kiểm tra xem có thay đổi nào để commit không
          git add public/data/auto/*
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update TFT data on $(date +'%d-%m-%Y')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}